portafolio/authapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signUp, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profileinfo/', views.profileinfo, name='profileinfo'),
]

portafolio/blogapp/contactapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.success_message, name='success_message'),
]

portafolio/contactapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact_view, name='contact'),
    path('success/', views.success_message, name='success_message'),
]

portafolio/portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include('homeapp.urls')),
    path('auth/', include('authapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('contact/', include('contactapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    


portafolio/blogapp/contactapp/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

portafolio/contactapp/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True, null=True)
    message = models.TextField()


    def __str__(self):
        return self.name

portafolio/blogapp/contactapp/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

portafolio/contactapp/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

portafolio/blogapp/contactapp/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_message')
    else:
        form = ContactForm()
    return render(request, 'contactapp/contact.html', {'form': form})

def success_message(request):
    return render(request, 'contactapp/success.html')

portafolio/contactapp/templates/contactapp/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block content %}
<div id="form" class="container mt-5">
    <h1>Contact Form</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Email address</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="id_phone" class="form-label">Phone</label>
            {{ form.phone }}
        </div><div class="mb-3">
            <label for="id_message" class="form-label">Message</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>
{% endblock %}

{% block style %}
<style>
    #form {
        width: 40%;
    }

    @media (max-width: 768px) {
        #form {
            width: 90%;
        }
    }
</style>
{% endblock %}

portafolio/contactapp/templates/contactapp/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container text-center mt-5">
        <h1>¡Mensaje enviado con éxito!</h1>
        <p>Gracias por contactarnos. Nos pondremos en contacto contigo pronto.</p>
    </div>
{% endblock %}